camera0: 4
camera1: 6
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 2.12
checkerboard_rows: 8
checkerboard_columns: 8
cooldown: 100